server:
  port: 8080

ai:
  url: ${AI_API_URL:https://api.4o.chat/v1}  # 修改为正确的4o-mini API地址
  key: ${AI_API_KEY:your-api-key}  # 使用环境变量

mcp:
  url: ${MCP_URL:http://localhost:8081/mcp/query}  # 修改为正确的MCP服务地址

logging:
  level:
    com.example.aidemo: DEBUG
  file:
    name: logs/ai-demo.log  # 添加日志文件配置
